[project]
name = "caritas-cda-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "boto3>=1.42.11",
    "click>=8.3.1",
    "dbt-core>=1.10.16",
    "dbt-snowflake>=1.10.4",
    "rich>=14.2.0",
]
